project:
  output-dir: ./docs/en

website:
  title: "Digital Ecology Scheme (DEN) Resources and Materials"
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright UMR MARBEC (IRD, Ifremer, Montpellier University, CNRS)"
  search:
    location: navbar
    type: textbox
    copy-button: true
    show-item-context: tree

  navbar:
    left:
      - text: "Overview"
        href: en/overview.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            href: https://github.com/umr-marbec/den_pages/issues
          - text: "Ask a Question"
            href: https://github.com/umr-marbec/den_pages/discussions
    right:
      - text: "English"
        href: ../en
      - text: "French"
        href: ../
    tools:
      - icon: github
        text: "Source code"
        href: https://github.com/umr-marbec/den_pages
      - icon: box-arrow-up-right
        text: "DEN Global Website"
        href: https://umr-marbec.fr/recherche/dispositifs-de-recherche/den/

  sidebar:
    style: "docked"
    contents:
      - text: "Introduction"
        href: en/introduction.qmd
      - section: "Version Control System"
        href: en/git/index_git.qmd
        contents:
          - text: "Mirroring from Github to a Git Repository"
            href: en/git/miroir_github_gitlab.qmd
      - section: "R Package"
        href: en/package_r/index_package_r.qmd
        contents:
          - text: "sparck"
            href: en/package_r/package_sparck.qmd

lang: en-US