project:
  title: "Ressources et supports du Dispositif d’Écologie Numérique (DEN)"
  output-dir: ./_site/

website:
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright UMR MARBEC (IRD, Ifremer, Montpellier university, CNRS)"
  search:
    location: navbar
    type: textbox
    copy-button: true
    show-item-context: tree
  navbar:
    left:
      - text: "Aperçu"
        href: pages/apercu.qmd
      - text: "Aide"
        menu:
          - text: "Signaler un bug"
            href: https://github.com/umr-marbec/den_pages/issues
          - text: "Poser une question"
            href: https://github.com/umr-marbec/den_pages/discussions
    right:
      - text: "Anglais"
        href: en
    tools:
      - icon: github
        text: "Code source"
        href: https://github.com/umr-marbec/den_pages
      - icon: box-arrow-up-right
        text: "Site global du DEN"
        href: https://umr-marbec.fr/recherche/dispositifs-de-recherche/den/
  sidebar:
    style: "docked"
    contents:
      - text: "Je veux contribuer !"
        href: pages/contribution.qmd
      - section: "Système de contrôle de version"
        href: pages/git/index_git.qmd
        contents:
          - text: "Miroir depuis Github vers un dépôt git"
            href: pages/git/miroir_github_gitlab.qmd
      - section: "Packages et logiciels"
        href: pages/packages_software/index_packages_software.qmd
        contents:
          - text: "Package R sparck"
            href: pages/packages_software/r_package_sparck.qmd

lan: fr