project:
  title: "Digital Ecology Scheme (DEN) Resources and Materials"
  output-dir: ./_site/en

website:
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright UMR MARBEC (IRD, Ifremer, Montpellier University, CNRS)"
  search:
    location: navbar
    type: textbox
    copy-button: true
    show-item-context: tree
  navbar:
    left:
      - text: "Overview"
        href: pages/apercu.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            href: https://github.com/umr-marbec/den_pages/issues
          - text: "Ask a Question"
            href: https://github.com/umr-marbec/den_pages/discussions
    right:
      - text: "French"
        href: ../
    tools:
      - icon: github
        text: "Source code"
        href: https://github.com/umr-marbec/den_pages
      - icon: box-arrow-up-right
        text: "DEN Global Website"
        href: https://umr-marbec.fr/recherche/dispositifs-de-recherche/den/
  sidebar:
    style: "docked"
    contents:
      - text: "I want to contribute!"
        href: pages/contribution.qmd
      - section: "Version Control System"
        href: pages/git/index_git.qmd
        contents:
          - text: "Mirroring from Github to a Git Repository"
            href: pages/git/miroir_github_gitlab.qmd
      - section: "Packages and software"
        href: pages/packages_software/index_packages_software.qmd
        contents:
          - text: "R package sparck"
            href: pages/packages_software/r_package_sparck.qmd

lang: en-US