project:
  type: website

execute:
  freeze: auto

website:
  title: "Site web de soutien du Dispositif d’Ecologie Numérique (DEN)"
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright UMR MARBEC (IRD, Ifremer, Montpellier university, CNRS)" 
  search:
    location: navbar
    type: textbox
    copy-button: true
    show-item-context: tree

  navbar:
    left:
      - text: "apercu"
        href: pages_fr/apercu.qmd
      - text: "Aide"
        menu:
          - text: "Signaler un bug"
            href: https://github.com/umr-marbec/den_pages/issues
          - text: "Poser une question"
            href: https://github.com/umr-marbec/den_pages/discussions
    tools:
      - icon: github
        text: "Code source"
        href: https://github.com/umr-marbec/den_pages
      - icon: box-arrow-up-right
        text: "Site global du DEN"
        href: https://umr-marbec.fr/recherche/dispositifs-de-recherche/den/

  sidebar:
    style: "docked"
    contents:
      - text: "Introduction"
        href: pages_fr/introduction.qmd
      - section: "Système de contrôle de version "
        href: index.qmd
        contents:
          - index.qmd
          - index.qmd
          - index.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

