project:
  type: website

website:
  site-url: https://luislaum.github.io/den_pages/
  favicon: images/favicon/favicon.ico
  title: "DEN Pages"
  navbar:
    right:
      - href: index.qmd
        text: "<span class='nav-center'>Accueil<br>Home</span>"
      - href: about.qmd
        text: "<span class='nav-center'>À propos<br>About</span>"
      - href: servers.qmd
        text: "<span class='nav-center'>Serveurs<br>Servers</span>"
      - href: softwaretraining.qmd
        text: "<span class='nav-center'>Logiciels & Formation<br>Software & Training</span>"
      - href: manualsguides.qmd
        text: "<span class='nav-center'>Manuels & Guides<br>Manuals & Guides</span>"
      - href: contact.qmd
        text: "<span class='nav-center'>Contact</span>"
  page-footer:
    left: © Copyright 2025, IRD-Marbec
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/umr-marbec/den_pages){target=_blank} and [Quarto](https://quarto.org/){target=_blank}


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

execute:
  freeze: true

