name: Deploy multi-language Quarto site to GitHub Pages

on:
  push:
    branches:
      - main  
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project french version
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: french
        with:
          to: html

      - name: Render Quarto Project french version
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: english
        with:
          to: html

      - name: Publish French Site
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target-branch: gh-pages
          target-path: ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish English Site
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target-branch: gh-pages
          target-path: ./docs/en
          site-prefix: en
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}